version: '2'
services:
  gateway:
    build: gateway
    ports:
      - "80:80"
      - "443:443"
    hostname: "kaazing.example.com"
  activemq:
    image: webcenter/activemq:5.10.0
    command: bash -c "sed -i 's/activemq-domain/activemq/g' /opt/activemq/conf/activemq.xml && /app/init start"
