version: '2'
services:
  gateway:
    build: gateway
    environment: 
      - GATEWAY_FEATURES=http.redirect
    ports:
      - "8000:8000"
      - "8001:8001"
    hostname: "kaazing.example.com"
  activemq:
    image: webcenter/activemq:5.10.0
    command: bash -c "sed -i 's/activemq-domain/activemq/g' /opt/activemq/conf/activemq.xml && /app/init start"
