version: '2'
services:
  gateway:
    build: gateway
    environment: 
      - GATEWAY_FEATURES=http.redirect
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    hostname: "kaazing.example.com"
  rabbitmq:
    build: broker
